Carregando o arquivo CSV para dentro do data frame

In [32]:
import pandas as pd
import numpy as np

df_steam = pd.read_csv('SteamGames.csv')
#Criando uma KPI
df_steam['Total_de_Vendas'] = (df_steam['PositiveReview'] + df_steam['PositiveReview']).astype(float)
df_steam.head()

,Appid,Name,Type,ReleaseDate,Genres,Developers,Publishers,Description,price,Thumbnail,Tags,ReviewScore,PositiveReview,NegativeReview,OsRequirement,MemoryRequirement,CpuRequirement,Rank,Total_de_Vendas
0,3764200,Resident Evil Requiem,game,"Feb 26, 2026","Action,Adventure","CAPCOM Co., Ltd.","CAPCOM Co., Ltd.",Resident Evil Requiem Deluxe Edition Resident ...,69.99$,https://shared.akamai.steamstatic.com/store_it...,NaN,9,23715,793,NaN,NaN,NaN,1,"47,430.00"
1,730,Counter-Strike 2,game,"Aug 21, 2012","Action,Free To Play",Valve,Valve,"For over two decades, Counter-Strike has offer...",0$,https://shared.akamai.steamstatic.com/store_it...,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",8,1214897,202393,Windows® 10,8 GB RAM,4 hardware CPU threads - Intel® Core™ i5 750 o...,2,"2,429,794.00"
2,1808500,ARC Raiders,game,"Oct 30, 2025",Action,Embark Studios,Embark Studios,ARC Raiders Deluxe Edition ARC Raiders Deluxe ...,39.99$,https://shared.akamai.steamstatic.com/store_it...,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",8,149531,23194,Windows 10 or later 64-bit (latest update),12 GB RAM,Intel Core i5-6600K or AMD Ryzen R5 1600 proce...,3,"299,062.00"
3,359550,Tom Clancy's Rainbow Six Siege,game,"Dec 1, 2015","Action,Free To Play",Ubisoft Montreal,Ubisoft,Season 11 Year 1 Overview Year 11 Roadmap Free...,0$,https://shared.akamai.steamstatic.com/store_it...,NaN,8,522886,106839,NaN,NaN,NaN,4,"1,045,772.00"
4,1172470,Apex Legends™,game,"Nov 4, 2020","Action,Adventure,Free To Play",Respawn,Electronic Arts,Apex Legends: Breach About the Game Conquer wi...,0$,https://shared.akamai.steamstatic.com/store_it...,"Free to Play,Multiplayer,Battle Royale,FPS,Sho...",6,820,216,64-bit Windows 10,6 GB RAM,"AMD FX 4350 or Equivalent, Intel Core i3 6300 ...",5,"1,640.00"

Sustitutindo dados vazios por dados consistentes.

In [33]:
substituicao_dados = {
    'Tags': 'Indie',
    'OsRequirement': 'Windows 11',
    'MemoryRequirement': '8 GB RAM',
    'CpuRequirement': 'Intel Core i5-3570K or AMD Ryzen 3 2200G'
}

df_steam.fillna(value=substituicao_dados, inplace=True)

,Appid,Name,Type,ReleaseDate,Genres,Developers,Publishers,Description,price,Thumbnail,Tags,ReviewScore,PositiveReview,NegativeReview,OsRequirement,MemoryRequirement,CpuRequirement,Rank,Total_de_Vendas
0,3764200,Resident Evil Requiem,game,"Feb 26, 2026","Action,Adventure","CAPCOM Co., Ltd.","CAPCOM Co., Ltd.",Resident Evil Requiem Deluxe Edition Resident ...,69.99$,https://shared.akamai.steamstatic.com/store_it...,Indie,9,23715,793,Windows 11,8 GB RAM,Intel Core i5-3570K or AMD Ryzen 3 2200G,1,"47,430.00"
1,730,Counter-Strike 2,game,"Aug 21, 2012","Action,Free To Play",Valve,Valve,"For over two decades, Counter-Strike has offer...",0$,https://shared.akamai.steamstatic.com/store_it...,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",8,1214897,202393,Windows® 10,8 GB RAM,4 hardware CPU threads - Intel® Core™ i5 750 o...,2,"2,429,794.00"
2,1808500,ARC Raiders,game,"Oct 30, 2025",Action,Embark Studios,Embark Studios,ARC Raiders Deluxe Edition ARC Raiders Deluxe ...,39.99$,https://shared.akamai.steamstatic.com/store_it...,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",8,149531,23194,Windows 10 or later 64-bit (latest update),12 GB RAM,Intel Core i5-6600K or AMD Ryzen R5 1600 proce...,3,"299,062.00"
3,359550,Tom Clancy's Rainbow Six Siege,game,"Dec 1, 2015","Action,Free To Play",Ubisoft Montreal,Ubisoft,Season 11 Year 1 Overview Year 11 Roadmap Free...,0$,https://shared.akamai.steamstatic.com/store_it...,Indie,8,522886,106839,Windows 11,8 GB RAM,Intel Core i5-3570K or AMD Ryzen 3 2200G,4,"1,045,772.00"
4,1172470,Apex Legends™,game,"Nov 4, 2020","Action,Adventure,Free To Play",Respawn,Electronic Arts,Apex Legends: Breach About the Game Conquer wi...,0$,https://shared.akamai.steamstatic.com/store_it...,"Free to Play,Multiplayer,Battle Royale,FPS,Sho...",6,820,216,64-bit Windows 10,6 GB RAM,"AMD FX 4350 or Equivalent, Intel Core i3 6300 ...",5,"1,640.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29926,843170,ILLUSION,game,"May 9, 2018","Adventure,Indie",LunaRolexLer,LunaRolexLer,Guilt Is The Feeling That Makes You Human. Thi...,1.99$,https://shared.akamai.steamstatic.com/store_it...,"Indie,Adventure,RPGMaker,Female Protagonist,Si...",7,39,2,Windows XP/Vista/7/8/10,100 MB RAM,Intel Core i5-3570K or AMD Ryzen 3 2200G,16715,78.00
29927,1308250,Knight Bewitched 2,game,"Aug 10, 2020","Adventure,Indie,RPG",Joshua Keith,Joshua Keith,Knight Bewitched 2 is a jRPG featuring the sto...,4.99$,https://shared.akamai.steamstatic.com/store_it...,"LGBTQ+,Female Protagonist,JRPG,Indie,Story Ric...",7,24,0,7 and above,2 GB RAM,2.2GHz dual-core,16716,48.00
29928,1729610,Redmatch 2 - Fashionable Attire Bundle,dlc,"Aug 17, 2021","Action,Free To Play,Indie",Rugbug Redfern,Rugbug Redfern,Bundle Content: Top Hat (Hat) Halo (Hat) Prope...,4.99$,https://shared.akamai.steamstatic.com/store_it...,"Action,Free to Play,Indie",0,7,1,Windows 7 or later,4 GB RAM,2.6 GHz Dual Core or similar,16717,14.00
29929,3956320,Inotia 4,game,"Dec 7, 2025","RPG,Free To Play",Com2uS,Com2uS,The grand adventure across the continent of In...,0$,https://shared.akamai.steamstatic.com/store_it...,"Singleplayer,RPG,2D,Fantasy,Pixel Graphics,Sto...",0,0,0,Windows 10 (64bit),8 GB RAM,Ryzen 2200g / Intel i3 8100,16718,0.00
29930,791180,1 Screen Platformer,game,"Mar 6, 2019","Action,Adventure,Indie","Return To Adventure Mountain, LLC","Return To Adventure Mountain, LLC",Get ready because the sequel is coming soon: T...,2.99$,https://shared.akamai.steamstatic.com/store_it...,"Precision Platformer,Difficult,2D Platformer,S...",8,147,22,Windows 7 or Later,1 GB RAM,2 GHz,16719,294.00

In [34]:
df_steam.info()

<class 'pandas.DataFrame'>
RangeIndex: 29931 entries, 0 to 29930
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Appid              29931 non-null  int64
 1   Name               29931 non-null  str
 2   Type               29931 non-null  str
 3   ReleaseDate        29917 non-null  str
 4   Genres             29518 non-null  str
 5   Developers         29905 non-null  str
 6   Publishers         28886 non-null  str
 7   Description        29879 non-null  str
 8   price              29931 non-null  str
 9   Thumbnail          29931 non-null  str
 10  Tags               29931 non-null  str
 11  ReviewScore        29931 non-null  int64
 12  PositiveReview     29931 non-null  int64
 13  NegativeReview     29931 non-null  int64
 14  OsRequirement      29931 non-null  str
 15  MemoryRequirement  29931 non-null  str
 16  CpuRequirement     29931 non-null  str
 17  Rank               29931 non-null  int64
 18  Total_de_Vendas    29931 non-null  float64
dtypes: float64(1), int64(5), str(13)
memory usage: 4.3 MB

Preenchendo os dados da coluna Genres vazios.

In [35]:
df_steam['Genres'] = df_steam['Genres'].fillna('Indie')

Organizando as datas de lançamento

In [36]:
df_steam['ReleaseDate'] = pd.to_datetime(df_steam['ReleaseDate'], format='%b %d, %Y', errors='coerce')
df_steam.dropna(subset=['ReleaseDate'], inplace=True)
df_steam.info()

<class 'pandas.DataFrame'>
Index: 29916 entries, 0 to 29930
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Appid              29916 non-null  int64
 1   Name               29916 non-null  str
 2   Type               29916 non-null  str
 3   ReleaseDate        29916 non-null  datetime64[us]
 4   Genres             29916 non-null  str
 5   Developers         29891 non-null  str
 6   Publishers         28872 non-null  str
 7   Description        29864 non-null  str
 8   price              29916 non-null  str
 9   Thumbnail          29916 non-null  str
 10  Tags               29916 non-null  str
 11  ReviewScore        29916 non-null  int64
 12  PositiveReview     29916 non-null  int64
 13  NegativeReview     29916 non-null  int64
 14  OsRequirement      29916 non-null  str
 15  MemoryRequirement  29916 non-null  str
 16  CpuRequirement     29916 non-null  str
 17  Rank               29916 non-null  int64
 18  Total_de_Vendas    29916 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(5), str(12)
memory usage: 4.6 MB

Filtrando dados de jogos AAA(Grandes Lançamentos)

In [37]:
# Converte a coluna price para conseguir ser lido.
df_steam['price'] = pd.to_numeric(
    df_steam['price'].astype(str)
        .str.replace(r'[^0-9.,]', '', regex=True)   
        .str.replace(',', '.', regex=False),        
    errors='coerce'                                 
).fillna(0.0)
condicao_year = (df_steam['ReleaseDate'].dt.year >= 2020) & (df_steam['ReleaseDate'].dt.year <= 2025)
condicao_price = (df_steam['price'] > 49.99)
condicao_review_player = (df_steam['PositiveReview'] > df_steam['NegativeReview'])

df_gamefilter_aaa = df_steam.loc[condicao_year & condicao_price & condicao_review_player]

print(f"Total de jogos filtrados (AAA): {len(df_gamefilter_aaa)}")

Total de jogos filtrados (AAA): 263

Teste de agrupamento

In [38]:
teste_agrupamento = df_gamefilter_aaa.groupby('Publishers').agg({'Name': 'count'})
print(teste_agrupamento)

                                         Name
Publishers
2K                                         10
2K Games                                    1
AEXLAB                                      1
Activision                                  3
Adobe                                       2
...                                       ...
YoYo Games Ltd.                             1
bulo studio                                 1
cub3                                        1
dramatic create                             2
iRacing.com Motorsport Simulations, LLC     1

[93 rows x 1 columns]

Recolhendo o total de vendas das 50 distribuidoras que mais venderam entre 2020 e 2025

In [39]:
pd.options.display.float_format = '{:,.2f}'.format
recolhimento = {
    'price': 'mean',
    'Total_de_Vendas': 'sum',}
df_gamefilter_aaa.groupby('Publishers').agg(recolhimento).sort_values(by='Total_de_Vendas', ascending=False).head(50)

                                                    price  Total_de_Vendas
Publishers
Larian Studios                                      59.99       844,006.00
FromSoftware, Inc.,Bandai Namco Entertainment       59.99       797,130.00
CD PROJEKT RED                                      59.99       651,004.00
Electronic Arts                                     66.24       597,286.00
Warner Bros. Games                                  59.99       306,126.00
PlayStation Publishing LLC                          59.99       303,234.00
2K                                                  64.99       248,974.00
SEGA                                                63.60       237,178.00
Xbox Game Studios                                   64.99       191,956.00
CAPCOM Co., Ltd.                                    63.99       171,394.00
Bethesda Softworks                                  65.99       163,196.00
Techland                                            59.99       147,794.00
Game Science                                        59.99       127,766.00
Valve                                               59.99       118,412.00
Deep Silver                                         59.99       112,092.00
Bandai Namco Entertainment                          61.66        85,442.00
SEGA,Feral Interactive                              59.99        83,522.00
FromSoftware, Inc.,Bandai Namco Entertainment Inc.  59.99        73,972.00
KONAMI                                              67.49        65,644.00
GSC Game World (worldwide),SEGA (Japan),4Divini...  59.99        63,174.00
Square Enix                                         60.58        63,088.00
NEOWIZ                                              69.99        48,300.00
Frontier Developments                               58.74        47,722.00
Eidos Interactive Corp.                             59.99        34,142.00
Activision                                          59.99        32,450.00
PlayStation Publishing LLC (excluding China)        59.99        28,782.00
Paradox Interactive                                 59.99        24,184.00
Bandai Namco Entertainment Inc.                     61.99        23,744.00
KRAFTON, Inc.                                       59.99        21,312.00
Focus Entertainment,4Divinity                       59.99        19,458.00
NEXON                                               59.99        16,856.00
NIS America, Inc.                                   59.99        14,586.00
LEVEL5 Inc.                                         64.99        13,634.00
BANDAI NAMCO Entertainment                          59.99        12,080.00
2K Games                                            59.99        11,980.00
KOEI TECMO GAMES CO., LTD.                          62.49        11,368.00
D3PUBLISHER                                         59.99         6,654.00
Aniplex Inc.                                        59.99         6,346.00
Rockstar Games                                      59.99         6,188.00
Bloober Team SA                                     59.99         5,966.00
Laminar Research                                    59.99         4,632.00
GungHo Online Entertainment America, Inc.           59.99         3,786.00
XSEED Games,Marvelous USA, Inc.,Marvelous Europe    64.99         3,204.00
Private Division                                    59.99         2,806.00
Spike Chunsoft Co., Ltd.                            59.99         2,036.00
Matrix Games                                        59.99         1,774.00
Gotcha Gotcha Games                                 89.99         1,748.00
iRacing.com Motorsport Simulations, LLC             59.99         1,728.00
Codemasters,Electronic Arts                         59.99         1,684.00
Spike Chunsoft Co., Ltd.                            59.99         1,452.00

Salvando a otimização feita.

In [40]:
df_steam.to_csv('SteamGames_clean.csv', index=False)